title: Chris McEvoy's Blog
author: "Chris McEvoy"
description: "Just what the world needs - another blog..."

theme: minima
show_excerpts: true
twitter_username: chrisimcevoy
github_username: chrisimcevoy

include:
    - _pages
